django/analyses/urls.py
from django.conf.urls import url
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from . import views

urlpatterns = [
    # Index URL loads dashboard homepage
    url(r'^$', views.index, name='index'),

    # analysis URL loads information for a particular analysis
    url(r'^(?P<anaid>[_A-Za-z0-9]+)/$', views.analysis, name='analysis'),

    # model URL loads information for a particular model
    url(r'^model/(?P<name>[_A-Za-z0-9]+)/$', views.model, name='model'),

    # blacklist URL loads information for a blacklist
    url(r'^(?P<anaid>[_A-Za-z0-9]+)/blacklists/$', views.blacklists, name='blacklists'),

    # pool URL loads information for a pool and associated analysis data
    url(r'^pool/(?P<pool>[_A-Za-z0-9]+)/$', views.pool, name='pools'),

    # Upload url allows upload of a new analysis
    url(r'^upload', views.model_form_upload, name='upload'),

    # export URL downloads a model
    url(r'^export', views.model_form_download, name='export'),

    # keyword URL provides all data for a keyword
    url(r'^keyword/(?P<key_word>[_A-Za-z0-9]+)/$', views.keywords_list, name='keyword'),

    # Runcard URL loads the relevent section of the app for presenting and adding runcard data
    url(r'^runcard/(?P<runcard_name>[_A-Za-z0-9]+)/$', views.Runcard, name='runcard'),

    # Results URL leads to results header page, which contains all results information
    url(r'^results/(?P<name>[_A-Za-z0-9]+)/$', views.results, name='results'),

    # Fetch keywords URL collects keywords data from inspire
    url(r'^fetch_keywords', views.upload_keywords, name='load_kws'),

    # Produce Heatmap URL collects runs generate heatmap script for active data and generates interactive heatmap using Bokeh
    url(r'^produce_heatmap/(?P<analyses>[_A-Za-z0-9]+)/$',views.heatmap_display, name='produce_heatmap'),

    # Positions URL loads second layer of YODA data, specifically around the data for each combination of parameters
    url(r'^positions/(?P<id>[_A-Za-z0-9]+)/$',views.positions, name='positions'),

    # ana_data URL loads all information for a .ana file
    url(r'^ana_data/(?P<id>[_A-Za-z0-9]+)/$',views.ana_data, name='ana_data'),

    # ufo_home URL loads ufo form to add new model using UFO link
    url(r'^ufo_home', views.ufo_home, name='ufo_home'),

    # Download HTML URL allows histogram HTML data to be downloaded in a zip file
    url(r'^download_html/(?P<id>[_A-Za-z0-9]+)/$', views.download_html, name='html_render'),

    # dl_bsm URL downloads a BSM model stored in local files
    url(r'^dl_bsm/(?P<name>[_A-Za-z0-9]+)/$', views.dl_bsm, name='dl_bsm'),

    # add_ana URL renders page to display user with different options for associating new .ana file to a model
    url(r'^add_ana/(?P<name>[_A-Za-z0-9]+)/$', views.add_ana, name='add_ana'),

    # [ana_file URL is to be removed]
    url(r'^ana_file/(?P<name>[_A-Za-z0-9]+)/$', views.ana_file_view, name='ana_file'),

    # add_existing_ana URL associates an existing .ana file with active model
    url(r'^add_existing_ana/(?P<modelname>[_A-Za-z0-9]+)/(?P<name>[_A-Za-z0-9]+)/$', views.add_existing_ana, name='add_existing_ana'),

    # inside_ana URL renders information about active .ana file
    url(r'^inside_ana/(?P<ana_name>[_A-Za-z0-9]+)/$', views.inside_ana, name='inside_ana'),

    # new_ana URL allows user to create new_ana file
    url(r'^new_ana/(?P<name>[_A-Za-z0-9]+)/$', views.new_ana, name='new_ana'),

    # write_ana URL exports .ana file in correct format
    url(r'^write_ana/(?P<name>[_A-Za-z0-9]+)/$', views.write_ana, name='write_ana'),

    # Pool input URL loads form to create a new analysis pool
    url(r'^pool_input', views.pool_form, name='pool_input'),

    # Render histo URL to render histogram image when link is clicked on results page
    url(r'^render_histo/(?P<id>[_A-Za-z0-9]+)/$', views.render_histo,name='render_histo'),

    # Upload new file attached to results header
    url(r'^create_file/(?P<name>[_A-Za-z0-9]+)/$', views.create_file,name='create_file'),

    # Upload new paper attached to results header
    url(r'^create_paper/(?P<name>[_A-Za-z0-9]+)/$', views.create_paper,name='create_paper'),

    # Download file by click
    url(r'^download_att_file/(?P<name>[_A-Za-z0-9]+)/$',views.download_att_file,name='download_att_file'),

    # Download paper by click
    url(r'^download_att_paper/(?P<name>[_A-Za-z0-9]+)/$',views.download_att_paper,name='download_att_paper'),

    # URL for personalisation search box
    url(r'^personalisation',views.personalisation,name='personalisation'),

    # URL for querying search box
    url(r'^querying',views.querying,name='querying'),

    # URL for exporting runcard parameter cards
    url(r'^runcard_export/(?P<name>[_A-Za-z0-9]+)/$',views.runcard_export,name='runcard_export'),

    # URL for calling rebuild yoda and exporting data
    url(r'^rebuild_yoda/(?P<id>[_A-Za-z0-9]+)/$',views.rebuild_yoda,name='rebuild_yoda'),

    # URL to load results form
    url(r'^results_form',views.results_form,name='results_form'),

    # URL for calling rebuild yoda for directory and exporting data
    url(r'^rebuild_yoda_dir/(?P<name>[_A-Za-z0-9]+)/$',views.rebuild_yoda_dir,name='rebuild_yoda_dir'),

    # URL for calling results header form
    url(r'^data_histo_ex/(?P<id>[_A-Za-z0-9]+)/$',views.data_histo_ex,name='data_histo_ex'),

    # URL for calling histogram data export view
    url(r'^image_histo_ex/(?P<id>[_A-Za-z0-9]+)/$', views.image_histo_ex, name='image_histo_ex')

]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

django/contur_db/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf.urls import url
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    url(r'^analyses/', include('analyses.urls')),
    url(r'^admin/', admin.site.urls),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

django/analyses/models.py
# Models.py: This defines all Django Models. These correspond to tables and columns within the database.
# This is a vital component of the Model-View-Template design pattern, and defines all data structures used.

from __future__ import unicode_literals

from django.db import models
from django.utils.encoding import python_2_unicode_compatible
import datetime
from mptt.models import MPTTModel, TreeForeignKey
from picklefield.fields import PickledObjectField



@python_2_unicode_compatible
class Analysis(models.Model):
    """
        Contains definition of Analysis model

        Analysis is linked to different models across the app:
        - Used to link Analyses to corresponding .ana files
        - Used to link Keywords to each Analyses
        - Used to link blacklist,subpool ,whitelist and normalisation to analyses

        Parameters:
        anaid (str): [Primary Key]: Name of Analyses: Should correspond to name in Rivet or HEPData
        lumi (float): Luminosity: Luminosity for given analysis
        pool ('Analysis Pool'): Pool that analysis corresponds to.
                                        [This is a foreign key link to the 'AnalysisPool' field]

        Returns:
            anaid

        db_table:
            analysis

    """
    anaid = models.TextField(primary_key=True)
    lumi = models.FloatField()
    pool = models.ForeignKey('AnalysisPool', on_delete=models.CASCADE, db_column='pool', blank=True, null=True)
    def __str__(self):
        return self.anaid

    class Meta:
        db_table = 'analysis'


@python_2_unicode_compatible
class AnalysisPool(models.Model):
    """
        Contains definition of AnalysisPool model

        AnalysisPool is linked to different models across the app:
        - Used to link Pool to Analysis

        Parameters:
        pool (str): [Primary Key]: Name of Pool

        Returns:
            pool

        db_table:
            analysis_pool

    """
    pool = models.TextField(primary_key=True)
    def __str__(self):
        return self.pool

    class Meta:
        db_table = 'analysis_pool'


@python_2_unicode_compatible
class Blacklist(models.Model):
    """
        Contains definition of Blacklist model

        Parameters:
        id (int): [Primary Key]
        anaid ('Analysis'): Analysis that Blacklist corresponds to.
                                        [This is a foreign key link to the 'Analysis' field]
        pattern (str): Pattern to be excluded

        Returns:
            anaid pattern

        db_table:
            blacklist

        """
    anaid = models.ForeignKey(Analysis, on_delete=models.CASCADE, db_column='anaid')
    pattern = models.TextField()
    def __str__(self):
        return '%s %s' % (self.anaid, self.pattern)

    class Meta:
        db_table = 'blacklist'


@python_2_unicode_compatible
class Normalization(models.Model):
    """
        Contains definition of Normalization model

        Parameters:
        id (int): [Primary Key]
        anaid ('Analysis'): Analysis that Normalization corresponds to.
                                        [This is a foreign key link to the 'Analysis' field]
        pattern (str): Pattern to be normalized
        norm (float): normalization factor
        scalemc (int): scale factor

        Returns:
            anaid pattern

        db_table:
            normalization

        """
    anaid = models.ForeignKey(Analysis, on_delete=models.CASCADE, db_column='anaid')
    pattern = models.TextField()
    norm = models.FloatField()
    scalemc = models.IntegerField()
    def __str__(self):
        return '%s %s' % (self.anaid, self.pattern)

    class Meta:
        db_table = 'normalization'
        unique_together = (('anaid', 'pattern'),)


@python_2_unicode_compatible
class Subpool(models.Model):
    """
        Contains definition of Subpool model

        Parameters:
        id (int): [Primary Key]
        anaid ('Analysis'): Analysis that Subpool corresponds to.
                                        [This is a foreign key link to the 'Analysis' field]
        pattern (str): Pattern corresponding to subpool
        subanaid (int): id of sub-analysis

        Returns:
            anaid pattern

        db_table:
            subpool

    """
    anaid = models.ForeignKey(Analysis, on_delete=models.CASCADE, db_column='anaid')
    pattern = models.TextField()
    subanaid = models.IntegerField()
    def __str__(self):
        return '%s %s' % (self.anaid, self.pattern)

    class Meta:
        db_table = 'subpool'
        unique_together = (('anaid', 'pattern'),)


@python_2_unicode_compatible
class Whitelist(models.Model):
    """
        Contains definition of Whitelist model

        Parameters:
        id (int): [Primary Key]
        anaid ('Analysis'): Analysis that Whitelist corresponds to.
                                        [This is a foreign key link to the 'Analysis' field]
        pattern (str): Pattern to be included

        Returns:
            anaid pattern

        db_table:
            whitelist

    """
    anaid = models.ForeignKey(Analysis, on_delete=models.CASCADE, db_column='anaid')
    pattern = models.TextField()
    def __str__(self):
        return '%s %s' % (self.anaid, self.pattern)

    class Meta:
        db_table = 'whitelist'


@python_2_unicode_compatible
class BSM_Model(models.Model):
    """
        Contains definition of BSM model:
            This represents the header of model, which links to runcards and then indirectly to results.
            This means that every result can be easily linked to the model header for querying and comparisons

        BSM_Model is linked to different models across the app:
        - Linked to used_analyses to link ana files to models
        - Linked to Download to select BSM model to download
        - Linked to Runcard to link individual runs to model header

        Parameters:
        name (str): [Primary Key]: Name Model
        UFO_Link (str): Link to feynrules raw download of UFO model -> This is used to download the model to the django files
        author (str): Name of creator -> used for Personal dashboard
        date_downloaded (DateTime): date created

        Returns:
            name

        db_table:
            bsm_model

    """
    name = models.CharField(max_length=100,primary_key=True)
    UFO_Link = models.TextField(blank=True)
    author = models.CharField(max_length=50)
    date_downloaded = models.DateField()


    def __str__(self):
        return self.name

    class Meta:
        db_table = 'bsm_model'


@python_2_unicode_compatible
class used_analyses(models.Model):
    """
        Contains definition of used_analyses model:
            One of 3 models used to link models, ana files and analyses together

        used_analyses is not directly linked to any models

        Parameters:
        id (int): [Primary Key]
        ana_name ('ana_list'): Corresponding ana file
                                        [This is a foreign key link to the 'ana_list' field]
        modelname ('BSM_Model'): Corresponding BSM_Model
                                        [This is a foreign key link to the 'BSM_Model' field]

        Returns:
            ana_name

        db_table:
            used_analyses

    """
    ana_name = models.ForeignKey('ana_list', on_delete=models.CASCADE, db_column='ana_name', blank=False, null=False)
    modelname = models.ForeignKey('BSM_Model', on_delete=models.CASCADE, db_column='model', blank=False, null=False)

    def __str__(self):
        return self.ana_name

    class Meta:
        db_table = 'used_analyses'
        unique_together = (('modelname', 'ana_name'),)

@python_2_unicode_compatible
class ana_file(models.Model):
    """
        Contains definition of ana_file model:
            One of 3 models used to link models, ana files and analyses together

        ana_file is not directly linked to any models

        Parameters:
        id (int): [Primary Key]
        ana_name ('ana_list'): Corresponding ana file
                                        [This is a foreign key link to the 'ana_list' field]
        anaid ('Analysis'): Corresponding Analysis
                                        [This is a foreign key link to the 'Analysis' field]

        Returns:
            linked_ana-anaid

        db_table:
            ana_file

    """
    linked_ana = models.ForeignKey('ana_list', on_delete=models.CASCADE, db_column='linked_ana', blank=False, null=False)
    anaid = models.ForeignKey('Analysis', on_delete=models.CASCADE, db_column='anaid', blank=False, null=False)

    def __str__(self):
        return '%s-%s' % (self.linked_ana, self.anaid)

    class Meta:
        db_table = 'ana_file'

@python_2_unicode_compatible
class ana_list(models.Model):
    """
        Contains definition of ana_list model:
            One of 3 models used to link models, ana files and analyses together
            Defines all ana file names

        ana_list is linked to different models across the app:
        - Linked to used_analyses to match ana files to the models they are used in
        - Linked to ana_file to match file names to the analyses within them

        Parameters:
        id (int): [Primary Key]
        ana_name (str): .ana file name
        author (str): name of creator

        Returns:
            linked_ana anaid

        db_table:
            analyses_ana_list

    """
    ana_name = models.CharField(max_length=50)
    author = models.CharField(max_length=50)

    def __str__(self):
        return self.ana_name


@python_2_unicode_compatible
class Download(models.Model):
    now = datetime.datetime.now()
    runcard_name = models.CharField(max_length=200, default=now.strftime("%d%m%Y%H%M"),primary_key=True)
    FILE_CHOICES = zip(BSM_Model.objects.all().values_list('name', flat=True) [0::1], BSM_Model.objects.all().values_list('name', flat=True)[0::1])
    Model = models.CharField(max_length=200, choices=FILE_CHOICES, default='')

django/analyses/forms.py
from django import forms
from .models import Download,runcard, BSM_Model,Analysis,AnalysisPool,attached_files,attached_papers,results_header


class DocumentForm(forms.ModelForm):
    class Meta:
        model = Analysis
        fields = ('anaid','lumi','pool',)

class PoolForm(forms.ModelForm):
    class Meta:
        model = AnalysisPool
        fields = ('pool',)

class DownloadForm(forms.ModelForm):
    class Meta:
        model = runcard
        fields = ('runcard_name','modelname','param_card','author',)

class UFOForm(forms.ModelForm):
    class Meta:
        model = BSM_Model
        fields = ('name','UFO_Link','author')

class AnalysesForm(forms.Form):

    OPTIONS = Analysis.objects.all()
    opts = []
    for value in OPTIONS:
        opts.append(tuple([value,value]))
    name = forms.CharField()
    author = forms.CharField()
    analyses = forms.MultipleChoiceField(widget=forms.CheckboxSelectMultiple,choices=opts)

class PaperForm(forms.ModelForm):
    class Meta:
        model = attached_papers
        fields = ('name','file',)

class FilesForm(forms.ModelForm):
    class Meta:
        model = attached_files
        fields = ('name','file',)

class ResultsForm(forms.ModelForm):
    class Meta:
        model = results_header
        fields = ('author','name','runcard','herwig_ver','contur_ver','rivet_ver',)

django/analyses/templates/analyses/add_ana.html
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd">

{% load static %}
    <html>
<head>
<style>
table {
    font-family: arial, sans-serif;
    border-collapse: collapse;
    width: 100%;
}

td, th {
    border: 1px solid #dddddd;
    text-align: left;
    padding: 8px;
}

tr:nth-child(even) {
    background-color: #dddddd;
}
</style>
</head>
<body>
      <meta http-equiv="Content-type" content="text/html;charset=UTF-8">
      <title>
        Contur Results and Data (CoDaR)
      </title>
      <link rel="shortcut icon" href="/favicon.ico">
      <link rel="stylesheet" type="text/css" href="{% static 'corad_page.css' %}">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <script type="text/javascript">
      var DOCUMENTATION_OPTIONS = {
        URL_ROOT:    './',
        VERSION:     '1.0',
        COLLAPSE_INDEX: false,
        FILE_SUFFIX: '.html',
        HAS_SOURCE:  true
      };
    </script>
    <script type="text/javascript" src="{% static 'jquery.js' %}"></script>
    <script type="text/javascript" src="{% static 'underscore.js' %}"></script>
    <script type="text/javascript" src="{% static 'doctools.js' %}"></script>
    <script type="text/javascript" src="https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML"></script>

        <div class="container">
            <div class="toppane"><h1>Link new .ana File</h1>
            <center><input type=button value="Previous Page" onClick="javascript:history.go(-1);"></center>
            <center> <input type=button value="Home" onClick="location.href='{% url 'index' %}'"></center>

            <div class="tleftpane"><h1><center>Linking To Model:</center></h1>
                {% if m %}
                    <h3>Name:</h3>{{m.name}}
                    <h3>UFO Link:</h3> {{m.UFO_Link}}
                    <h3>Author:</h3> {{m.author}}
                    <h3>Date Loaded:</h3>  {{m.date_downloaded}}
                {% endif %}
            </div>
            <div class="tmiddlepane"><h1><center>Add Existing .ana</center></h1>
                {% if anas %}
                        <table>
                            <tr>
                                <th>Name</th>
                                <th>Author</th>
                                <th></th>
                            </tr>
                        {% for ana in anas %}
                            {% cycle '' '<tr>'%}
                                <td><a href="{% url 'inside_ana' ana.ana_name %}">{{ ana.ana_name }}</a></td>
                                <td>{{ ana.author }}</td>
                                <td><a href="{% url 'add_existing_ana' m.name ana.ana_name %}">Link to this Model</a></td>
                            {% cycle '' '</tr>' %}
                        {% endfor %}
                        </table>
                {% else %}
                        <p>No analyses are available.</p>
                {% endif %}
            </div>

            <div class="trightpane"><h1><center>Create new .ana</center></h1>
                <center><a href="{% url 'new_ana' m.name %}" class="button">Create (and link) New Ana File</a></center>
            </div>
        </div>

django/analyses/templates/analyses/file_upload.html
<h1>Add file to results record</h1>
{{warning}}
{% block content %}
                <form method="post" enctype="multipart/form-data">
                  {% csrf_token %}
                  {{ form.as_p }}
                  <button type="submit">Upload</button>
                </form>
{% endblock %}

<center><input type=button value="Previous Page" onClick="javascript:history.go(-1);"></center>
<center> <input type=button value="Home" onClick="location.href='{% url 'index' %}'"></center>

django/analyses/templates/analyses/histo_data_nf.html
Histogram Data has not been uploaded, please run "dat2db.py -r RESULTSNAME -d DIRECTORYNAME" on the results data.
<ul>
<img src="{{MEDIA_URL}}stop.png">
</ul>
<ul>
<input type=button value="Previous Page" onClick="javascript:history.go(-1);">
</ul>

<center><input type=button value="Previous Page" onClick="javascript:history.go(-1);"></center>
<center> <input type=button value="Home" onClick="location.href='{% url 'index' %}'"></center>

django/analyses/templates/analyses/index.html
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd">

{% load static %}
    <html>
<head>
<style>
table {
    font-family: arial, sans-serif;
    border-collapse: collapse;
    width: 100%;
}

td, th {
    border: 1px solid #dddddd;
    text-align: left;
    padding: 8px;
}

tr:nth-child(even) {
    background-color: #dddddd;
}
</style>
</head>
<body>
      <meta http-equiv="Content-type" content="text/html;charset=UTF-8">
      <title>
        Contur Results and Data (Cord)
      </title>
      <link rel="shortcut icon" href="/favicon.ico">
      <link rel="stylesheet" type="text/css" href="{% static 'corad.css' %}">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <script type="text/javascript">
      var DOCUMENTATION_OPTIONS = {
        URL_ROOT:    './',
        VERSION:     '1.0',
        COLLAPSE_INDEX: false,
        FILE_SUFFIX: '.html',
        HAS_SOURCE:  true
      };
    </script>
    <script type="text/javascript" src="{% static 'jquery.js' %}"></script>
    <script type="text/javascript" src="{% static 'underscore.js' %}"></script>
    <script type="text/javascript" src="{% static 'doctools.js' %}"></script>
    <script type="text/javascript" src="https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML"></script>

        <div class="container">
            <div class="toppane"><h1>Contur Results and Data (Cord)</h1>

        <form id="searchform" action="{% url 'personalisation'%}" method="get" accept-charset="utf-8">
          <button class="searchbutton" type="submit" style="height:40px;width:100px">
            <i class="fa fa-search"></i>View User Dashboard
          </button>
          <input class="searchfield" id="searchbox" name="q" type="text" placeholder="Author/Creator Name">
        </form>


        <form id="searchform2" action="{% url 'querying'%}" method="get" accept-charset="utf-8">
          <button class="searchbutton" type="submit" style="height:40px;width:100px">
            <i class="fa fa-search"></i>Search Data
          </button>
          <input class="searchfield" id="searchbox2" name="q" type="text" placeholder="Data Content">
        </form>

        <form action="{% url 'index'%}">
            <input type="submit" value="Return to Home" />
        </form>



        </div>

            <div class="tleftpane"><h1><center>Contur BSM Models</center></h1>
                <center><a href="{% url 'ufo_home' %}" class="button">Add New BSM Model</a></center>
                {% if models_list %}
                    <table>
                        <tr>
                        <th>Name</th>
                            </tr>
                    {% for m in models_list %}
                        {% cycle '' '<tr>'%}
                            <td><a href="{% url 'model' m.name %}">{{ m.name }}</a></td>
                        {% cycle '' '</tr>' %}
                    {% endfor %}
                    </table>
                {% else %}
                    <p>No model scans are available.</p>
                {% endif %}
            </div>

            <div class="trightpane"><h1><center>Results</center></h1>
                <center><a href="{% url 'results_form' %}" class="button">Create Results Object</a></center>
                    {% if results_list %}
                        <table>
                            <tr>
                        <th>Name</th>
                                <th>Model</th>
                                <th>Creator</th>
                            </tr>
                        {% for n in results_list %}
                            {% cycle '' '<tr>'%}
                                <td><a href="{% url 'results' n.name %}">{{ n.name}}</a></td>
                                <td>{{n.runcard.modelname}}</td>
                                <td>{{n.author}}</td>
                            {% cycle '' '</tr>' %}
                        {% endfor %}
                        </table>
                    {% else %}
                        <p>No results are available.</p>
                    {% endif %}

            </div>


            <div class="bleftpane"><h1><center>Runcards</center></h1>
                <center><a href="{% url 'export' %}" class="button">Create Run Card</a></center>
                {% if runcard_list %}

                    <table>
                        <tr>
                        <th>Name</th>
                                <th>Author</th>
                                <th>Model</th>
                            <th>Date</th>
                            </tr>
                    {% for r in runcard_list %}
                        {% cycle '' '<tr>'%}
                            <td><a href="{% url 'runcard' r.runcard_name %}">{{ r.runcard_name }}</a></td>
                            <td>{{r.author}}</td>
                            <td>{{r.modelname}}</td>
                            <td>{{r.now}}</td>
                        {% cycle '' '</tr>' %}
                    {% endfor %}
                    </table>
                {% else %}
                    <p>No results are available.</p>
                {% endif %}
            </div>
            <div class="bmiddlepane"><h1><center>Analyses</center></h1>
                <center><a href="{% url 'upload' %}" class="button">Upload Analyses</a></center>
                {% if analysis_list %}
                    <table>
                        <tr>
                        <th>Analysis</th>
                        <th>Luminosity Factor</th>
                        <th>Pool</th>
                        </tr>
                    {% for ana in analysis_list %}
                        {% cycle '' '<tr>'%}
                            <td><a href="{% url 'analysis' ana.anaid %}">{{ ana.anaid }}</a></td>
                            <td>{{ ana.lumi }}</td> <td>{{ ana.pool }}</td>
                        {% cycle '' '</tr>' %}
                    {% endfor %}
                    </table>
                {% else %}
                    <p>No analyses are available.</p>
                {% endif %}
            </div>
            <div class="brightpane"><h1><center>Analyses Pools</center></h1>
                    <center><a href="{% url 'pool_input' %}" class="button">New Pool</a></center>
                    {% if analysis_pools %}
                        <table>
                            <tr>
                        <th>Pool</th>
                        <th>Analysis Count</th>
                            </tr>
                        {% for pool in analysis_pools %}
                            {% cycle '' '<tr>'%}
                                <td><a href="{% url 'pools' pool.pool %}">{{ pool.pool }}</a></td>
                                <td>[{{ pool.analysis_set.all | length }}]</td>
                            {% cycle '' '</tr>' %}
                        {% endfor %}
                        </table>
                    {% else %}
                        <p>No analyses are available.</p>
                    {% endif %}
            </div>
        </div>

django/analyses/templates/analyses/pool.html
<h1>Contur pool {{ pool.pool }}</h1>

<h2>Related Analyses</h2>
{% if pool.analysis_set.all %}
    <ul>
    {% for ana in pool.analysis_set.all %}
        <li>
        	<a href="{% url 'analysis' ana.anaid %}">{{ ana.anaid }}</a>:
        	luminosity factor {{ ana.lumi }} 
        </li>
    {% endfor %}
    </ul>
{% else %}
    <p>No analyses are available.</p>
{% endif %}

<center><input type=button value="Previous Page" onClick="javascript:history.go(-1);"></center>
<center> <input type=button value="Home" onClick="location.href='{% url 'index' %}'"></center>